import { GitBranch, GitPullRequest } from "lucide-react";
import type { ChangeSet } from "@/lib/api";
import { usd } from "@/lib/utils";
import { Dialog } from "./ui";
import { CodeBlock, CopyButton } from "./Code";

function diffLines(a: string, b: string) {
  const A = a.split("\n");
  const B = b.split("\n");
  const setA = new Set(A.map((l) => l.trim()));
  const setB = new Set(B.map((l) => l.trim()));
  return [
    ...A.filter((l) => !setB.has(l.trim())).map((l) => ({ t: "-", l })),
    ...B.filter((l) => !setA.has(l.trim())).map((l) => ({ t: "+", l })),
  ];
}

export function PrModal({ c, onClose }: { c: ChangeSet | null; onClose: () => void }) {
  if (!c) return <Dialog open={false} onOpenChange={onClose} title="" />;
  const rule = (c.rule_ids || ["rule"])[0];
  const id8 = c.change_set_id.slice(0, 8);
  const branch = `bqopt/${rule.toLowerCase()}-${id8}`;
  const table = c.target_table || "query";
  const file = `models/analytics/${c.target_dataset}/${table}.sql`;
  const cur = String(c.evidence?.current_sql || "");
  const prop = String(c.evidence?.proposed_sql || c.proposed?.generated_ddl || "");
  const net = Math.round(Number(c.net_monthly_value_usd || 0)).toLocaleString();
  const cli = `gh pr create --base main --head ${branch} --title "perf(${table}): [${rule}] Optimize SQL query to save $${net}/mo" --body "Automated BigQuery Optimization PR generated by Control Plane."`;
  const diff = diffLines(cur, prop);

  return (
    <Dialog
      open={!!c}
      onOpenChange={(o) => !o && onClose()}
      className="max-w-3xl"
      title={
        <span className="flex items-center gap-2">
          <GitPullRequest className="h-4 w-4 text-violet-400" />
          GitHub pull request · {usd(c.net_monthly_value_usd)}/mo
        </span>
      }
      description="Class 4 rewrites ship through code review instead of being applied directly."
    >
      <div className="max-h-[65vh] space-y-4 overflow-y-auto">
        <div className="grid gap-3 sm:grid-cols-2">
          <div className="rounded-lg border border-zinc-200 p-3 dark:border-ink-800">
            <div className="label">Branch</div>
            <div className="mt-1 flex items-center gap-1 font-mono text-xs">
              <GitBranch className="h-3.5 w-3.5 text-zinc-500" />{branch}<CopyButton text={branch} />
            </div>
          </div>
          <div className="rounded-lg border border-zinc-200 p-3 dark:border-ink-800">
            <div className="label">File</div>
            <div className="mt-1 flex items-center gap-1 break-all font-mono text-xs">{file}<CopyButton text={file} /></div>
          </div>
        </div>
        <div className="overflow-hidden rounded-lg border border-zinc-200 dark:border-ink-800">
          <div className="border-b border-zinc-800 bg-zinc-900 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wider text-zinc-400">Diff</div>
          <pre className="max-h-64 overflow-auto bg-zinc-950 p-3 font-mono text-[12px] leading-relaxed">
            {diff.length === 0 && <span className="text-zinc-500">No textual difference detected.</span>}
            {diff.map((d, i) => (
              <div key={i} className={d.t === "-" ? "bg-rose-500/10 text-rose-300" : "bg-emerald-500/10 text-emerald-300"}>
                {d.t} {d.l}
              </div>
            ))}
          </pre>
        </div>
        <CodeBlock code={cli} title="Create with GitHub CLI" tone="sky" />
      </div>
    </Dialog>
  );
}
