"""Class 4 / CI_PULL_REQUEST hand-off (Option B — no GitHub token needed).

Class 4 recommendations are SQL rewrites that live in someone's code (dbt model,
dashboard, app), so the optimizer never applies them directly. Instead of being
skipped forever, an approved card is *handed off*: the executor builds everything
an engineer needs to open the pull request (branch, file path, commit message,
PR title/body, copy-paste git + gh commands, the rewritten SQL) and moves the
card to PR_HANDED_OFF. When the PR is merged, a reviewer clicks "Mark PR merged"
in the UI, which moves the card to APPLIED -> VERIFYING so realized savings are
measured like any other change.

Lifecycle:  APPROVED -> PR_HANDED_OFF -> (PR merged) -> APPLIED -> VERIFYING -> ...
"""
from __future__ import annotations

import datetime as dt
import re

from .. import bq
from ..config import Config

HANDOFF_STATE = "PR_HANDED_OFF"


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9._-]+", "-", (s or "").lower()).strip("-") or "query"


def build(c: Config, cs: dict) -> dict:
    """Pure: builds the PR hand-off package from a change-set row (no side effects)."""
    ev = cs.get("evidence") if isinstance(cs.get("evidence"), dict) else (bq.loads(cs.get("evidence_json")) or {})
    pr = cs.get("proposed") if isinstance(cs.get("proposed"), dict) else (bq.loads(cs.get("proposed_change_json")) or {})
    rule = ((cs.get("rule_ids") or ["rule"])[0]) or "rule"
    cs_id = cs["change_set_id"]
    table = cs.get("target_table") or "query"
    dataset = cs.get("target_dataset") or "analytics"
    net = float(cs.get("net_monthly_value_usd") or cs.get("gross_monthly_savings_usd") or 0)

    branch = f"bqopt/{_slug(rule)}-{cs_id[:8]}"
    file_path = f"models/analytics/{_slug(dataset)}/{_slug(table)}.sql"
    current_sql = str(ev.get("current_sql") or "")
    proposed_sql = str(ev.get("proposed_sql") or pr.get("rewrite_template") or pr.get("generated_ddl") or "")
    title = f"perf({table}): [{rule}] Optimize SQL query to save ${net:,.0f}/mo"
    body = "\n".join([
        f"Automated BigQuery Optimization PR generated by the Control Plane (change set `{cs_id}`).",
        "",
        f"**Rule:** {rule}",
        f"**Target:** `{cs.get('target_project')}.{dataset}.{table}`",
        f"**Estimated savings:** ${net:,.2f} / month",
        f"**Why:** {cs.get('finding_summary') or ''}".strip(),
        "",
        "Validate query results match before merging. After merge, mark the PR as merged in the",
        "review UI so the optimizer starts measuring realized savings.",
    ])
    commit_msg = f"perf({table}): apply {rule} BigQuery optimization ({cs_id[:8]})"
    git_cmds = "\n".join([
        f"git checkout -b {branch}",
        f"# replace the query in {file_path} with the proposed SQL below",
        f"git add {file_path}",
        f'git commit -m "{commit_msg}"',
        f"git push -u origin {branch}",
    ])
    gh_cmd = (f'gh pr create --base main --head {branch} --title "{title}" '
              f'--body "Automated BigQuery Optimization PR generated by Control Plane (change set {cs_id})."')
    return {
        "type": "PR_HANDOFF",
        "handed_off_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "branch": branch,
        "file_path": file_path,
        "commit_message": commit_msg,
        "pr_title": title,
        "pr_body": body,
        "git_commands": git_cmds,
        "gh_command": gh_cmd,
        "current_sql": current_sql,
        "proposed_sql": proposed_sql,
        "pr_url": None,
    }


def hand_off(c: Config, cs: dict, actor: str = "executor") -> dict:
    """Moves an approved CI_PULL_REQUEST card to PR_HANDED_OFF and stores the package."""
    from .. import store
    pkg = build(c, cs)
    store.transition(c, cs["change_set_id"], HANDOFF_STATE, actor,
                     note=f"Handed off for code review: open a PR from branch {pkg['branch']} "
                          f"({pkg['file_path']}), then click 'Mark PR merged' in the review UI.",
                     extra={"progress_json": bq.dumps(pkg)})
    return pkg


def mark_merged(c: Config, cs: dict, actor: str, pr_url: str | None = None) -> None:
    """PR merged -> APPLIED -> VERIFYING. Baseline is frozen first so verification has a 'before'."""
    from .. import store, verifier
    if cs.get("state") != HANDOFF_STATE:
        raise ValueError(f"change set is {cs.get('state')}, expected {HANDOFF_STATE}")
    pr_url = (pr_url or "").strip() or None
    if pr_url and not re.match(r"^https?://", pr_url):
        raise ValueError("PR link must start with http:// or https://")
    pkg = bq.loads(cs.get("progress_json")) or {}
    pkg["pr_url"] = pr_url
    pkg["merged_at"] = dt.datetime.now(dt.timezone.utc).isoformat()
    pkg["merged_by"] = actor
    verifier.freeze_baseline(c, cs)
    now = bq.query(c, "SELECT CURRENT_TIMESTAMP() AS t")[0]["t"].isoformat()
    store.transition(c, cs["change_set_id"], "APPLIED", actor,
                     note=f"PR merged{': ' + pr_url if pr_url else ''}",
                     extra={"progress_json": bq.dumps(pkg), "applied_at": now,
                            "rollback_plan_json": bq.dumps({"type": "REVERT_PR", "pr_url": pr_url,
                                                            "branch": pkg.get("branch")})})
    store.transition(c, cs["change_set_id"], "VERIFYING", actor,
                     note="Measuring realized savings on the rewritten query family")
