#!/usr/bin/env python3
"""Demo helper to render or create GitHub Pull Requests for Class 4 change sets."""

import os
import sys

# Auto-reexec with local virtualenv if invoked with system python
if sys.prefix == sys.base_prefix:
    _base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for _vpy in [
        os.path.join(_base_dir, ".venv", "bin", "python"),
        os.path.join(_base_dir, ".venv", "bin", "python3"),
        os.path.join(os.path.expanduser("~"), ".venv-bq", "bin", "python"),
        os.path.join(os.path.expanduser("~"), ".venv-bq", "bin", "python3"),
    ]:
        if os.path.exists(_vpy):
            os.execv(_vpy, [_vpy] + sys.argv)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from optimizer import bq, store
from optimizer.config import cfg

def create_pr(change_set_id: str, repo: str | None = None) -> None:
    c = cfg()
    cs = store.get(c, change_set_id)
    if not cs:
        sys.exit(f"❌ Error: Change set '{change_set_id}' not found.")
    
    ev = bq.loads(cs.get("evidence_json")) or {}
    prop = bq.loads(cs.get("proposed_change_json")) or {}
    
    q_hash = ev.get("query_hash") or cs.get("target_table") or "query_rewrite"
    rule_ids = cs.get("rule_ids") or ["C4-01"]
    rule_code = rule_ids[0] if isinstance(rule_ids, list) and rule_ids else "C4-01"
    
    branch = f"bq-optimizer/{rule_code.lower()}-{q_hash[:12]}"
    file_path = f"models/analytics/{cs.get('target_dataset', 'queries')}/{q_hash}.sql"
    
    before_sql = ev.get("sample_preview") or cs.get("current_config_ddl") or "SELECT * FROM dataset.table;"
    after_sql = prop.get("generated_ddl") or ev.get("underlying_sql") or "-- Optimized SQL"
    
    print("\n" + "="*80)
    print("🚀 GITHUB PULL REQUEST GENERATOR — CONTROL PLANE CI/CD BOT")
    print("="*80)
    print(f"📌 Change Set ID:  {cs.get('change_set_id')}")
    print(f"🎯 Target Query:   {cs.get('target_project')}.{cs.get('target_dataset')}.{cs.get('target_table')}")
    print(f"🌿 Git Branch:     {branch}")
    print(f"📄 Modified File:   {file_path}")
    print(f"💰 Net Value:      ${float(cs.get('net_monthly_value_usd') or 0):,.2f} / month")
    print("-" * 80)
    print("📝 PULL REQUEST TITLE:")
    print(f"   perf({cs.get('target_table')}): [{rule_code}] Optimize SQL query to save ${float(cs.get('net_monthly_value_usd') or 0):,.0f}/mo")
    print("-" * 80)
    print("📋 PULL REQUEST DESCRIPTION:")
    print("   Automated optimization generated by BigQuery Optimization Control Plane.")
    print(f"   - Rule Triggered: {rule_code}")
    print(f"   - Confidence Score: {float(cs.get('confidence') or 0.7)*100:.0f}%")
    print(f"   - Estimated Monthly Savings: ${float(cs.get('net_monthly_value_usd') or 0):,.2f} / month")
    print("-" * 80)
    print("🔍 UNIFIED GIT DIFF:")
    print(f"--- a/{file_path}")
    print(f"+++ b/{file_path}")
    for line in before_sql.splitlines():
        print(f"- {line}")
    for line in after_sql.splitlines():
        print(f"+ {line}")
    print("-" * 80)
    
    target_repo = repo or "github.com/your-org/bq-analytics-dbt"
    print(f"🔗 SIMULATED GITHUB PR URL:\n   https://{target_repo}/pull/42\n")
    print("="*80 + "\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("usage: demo_git_pr.py <change_set_id> [repo]")
    create_pr(sys.argv[1], repo=sys.argv[2] if len(sys.argv) > 2 else None)
